/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo3.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "demo3.pb-c.h"
void   marvell__plr_rx_qc_status_t__init
                     (Marvell__PlrRxQcStatusT         *message)
{
  static const Marvell__PlrRxQcStatusT init_value = MARVELL__PLR_RX_QC_STATUS_T__INIT;
  *message = init_value;
}
size_t marvell__plr_rx_qc_status_t__get_packed_size
                     (const Marvell__PlrRxQcStatusT *message)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_status_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_rx_qc_status_t__pack
                     (const Marvell__PlrRxQcStatusT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_status_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_rx_qc_status_t__pack_to_buffer
                     (const Marvell__PlrRxQcStatusT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_status_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrRxQcStatusT *
       marvell__plr_rx_qc_status_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrRxQcStatusT *)
     protobuf_c_message_unpack (&marvell__plr_rx_qc_status_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_rx_qc_status_t__free_unpacked
                     (Marvell__PlrRxQcStatusT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_rx_qc_status_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_advanced_rules_t__init
                     (Marvell__PlrAdvancedRulesT         *message)
{
  static const Marvell__PlrAdvancedRulesT init_value = MARVELL__PLR_ADVANCED_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_advanced_rules_t__get_packed_size
                     (const Marvell__PlrAdvancedRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_advanced_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_advanced_rules_t__pack
                     (const Marvell__PlrAdvancedRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_advanced_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_advanced_rules_t__pack_to_buffer
                     (const Marvell__PlrAdvancedRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_advanced_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrAdvancedRulesT *
       marvell__plr_advanced_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrAdvancedRulesT *)
     protobuf_c_message_unpack (&marvell__plr_advanced_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_advanced_rules_t__free_unpacked
                     (Marvell__PlrAdvancedRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_advanced_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_rx_qc_rules_t__init
                     (Marvell__PlrRxQcRulesT         *message)
{
  static const Marvell__PlrRxQcRulesT init_value = MARVELL__PLR_RX_QC_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_rx_qc_rules_t__get_packed_size
                     (const Marvell__PlrRxQcRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_rx_qc_rules_t__pack
                     (const Marvell__PlrRxQcRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_rx_qc_rules_t__pack_to_buffer
                     (const Marvell__PlrRxQcRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrRxQcRulesT *
       marvell__plr_rx_qc_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrRxQcRulesT *)
     protobuf_c_message_unpack (&marvell__plr_rx_qc_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_rx_qc_rules_t__free_unpacked
                     (Marvell__PlrRxQcRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_rx_qc_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_lm_rules_t__init
                     (Marvell__PlrLmRulesT         *message)
{
  static const Marvell__PlrLmRulesT init_value = MARVELL__PLR_LM_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_lm_rules_t__get_packed_size
                     (const Marvell__PlrLmRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_lm_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_lm_rules_t__pack
                     (const Marvell__PlrLmRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_lm_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_lm_rules_t__pack_to_buffer
                     (const Marvell__PlrLmRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_lm_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrLmRulesT *
       marvell__plr_lm_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrLmRulesT *)
     protobuf_c_message_unpack (&marvell__plr_lm_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_lm_rules_t__free_unpacked
                     (Marvell__PlrLmRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_lm_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_bundles_rules_t__init
                     (Marvell__PlrBundlesRulesT         *message)
{
  static const Marvell__PlrBundlesRulesT init_value = MARVELL__PLR_BUNDLES_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_bundles_rules_t__get_packed_size
                     (const Marvell__PlrBundlesRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_bundles_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_bundles_rules_t__pack
                     (const Marvell__PlrBundlesRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_bundles_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_bundles_rules_t__pack_to_buffer
                     (const Marvell__PlrBundlesRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_bundles_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrBundlesRulesT *
       marvell__plr_bundles_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrBundlesRulesT *)
     protobuf_c_message_unpack (&marvell__plr_bundles_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_bundles_rules_t__free_unpacked
                     (Marvell__PlrBundlesRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_bundles_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_lrx_rules_t__init
                     (Marvell__PlrLrxRulesT         *message)
{
  static const Marvell__PlrLrxRulesT init_value = MARVELL__PLR_LRX_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_lrx_rules_t__get_packed_size
                     (const Marvell__PlrLrxRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_lrx_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_lrx_rules_t__pack
                     (const Marvell__PlrLrxRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_lrx_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_lrx_rules_t__pack_to_buffer
                     (const Marvell__PlrLrxRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_lrx_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrLrxRulesT *
       marvell__plr_lrx_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrLrxRulesT *)
     protobuf_c_message_unpack (&marvell__plr_lrx_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_lrx_rules_t__free_unpacked
                     (Marvell__PlrLrxRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_lrx_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_hrx_rules_t__init
                     (Marvell__PlrHrxRulesT         *message)
{
  static const Marvell__PlrHrxRulesT init_value = MARVELL__PLR_HRX_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_hrx_rules_t__get_packed_size
                     (const Marvell__PlrHrxRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_hrx_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_hrx_rules_t__pack
                     (const Marvell__PlrHrxRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_hrx_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_hrx_rules_t__pack_to_buffer
                     (const Marvell__PlrHrxRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_hrx_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrHrxRulesT *
       marvell__plr_hrx_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrHrxRulesT *)
     protobuf_c_message_unpack (&marvell__plr_hrx_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_hrx_rules_t__free_unpacked
                     (Marvell__PlrHrxRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_hrx_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_tx_rules_t__init
                     (Marvell__PlrTxRulesT         *message)
{
  static const Marvell__PlrTxRulesT init_value = MARVELL__PLR_TX_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_tx_rules_t__get_packed_size
                     (const Marvell__PlrTxRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_tx_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_tx_rules_t__pack
                     (const Marvell__PlrTxRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_tx_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_tx_rules_t__pack_to_buffer
                     (const Marvell__PlrTxRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_tx_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrTxRulesT *
       marvell__plr_tx_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrTxRulesT *)
     protobuf_c_message_unpack (&marvell__plr_tx_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_tx_rules_t__free_unpacked
                     (Marvell__PlrTxRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_tx_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_rules_t__init
                     (Marvell__PlrRulesT         *message)
{
  static const Marvell__PlrRulesT init_value = MARVELL__PLR_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_rules_t__get_packed_size
                     (const Marvell__PlrRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_rules_t__pack
                     (const Marvell__PlrRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_rules_t__pack_to_buffer
                     (const Marvell__PlrRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrRulesT *
       marvell__plr_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrRulesT *)
     protobuf_c_message_unpack (&marvell__plr_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_rules_t__free_unpacked
                     (Marvell__PlrRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor marvell__plr_rx_qc_status_t__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRxQcStatusT, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_rx_qc_status_t__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange marvell__plr_rx_qc_status_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor marvell__plr_rx_qc_status_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_rx_qc_status_t",
  "PlrRxQcStatusT",
  "Marvell__PlrRxQcStatusT",
  "marvell",
  sizeof(Marvell__PlrRxQcStatusT),
  1,
  marvell__plr_rx_qc_status_t__field_descriptors,
  marvell__plr_rx_qc_status_t__field_indices_by_name,
  1,  marvell__plr_rx_qc_status_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_rx_qc_status_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_advanced_rules_t__field_descriptors[7] =
{
  {
    "fll_low_bw_en",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, fll_low_bw_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ldo_mode_pll",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, ldo_mode_pll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ldo_mode_txrx",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, ldo_mode_txrx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gck_en",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, gck_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "breakout_en",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, breakout_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "los_thresholds_en",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, los_thresholds_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avs_en",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, avs_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_advanced_rules_t__field_indices_by_name[] = {
  6,   /* field[6] = avs_en */
  4,   /* field[4] = breakout_en */
  0,   /* field[0] = fll_low_bw_en */
  3,   /* field[3] = gck_en */
  1,   /* field[1] = ldo_mode_pll */
  2,   /* field[2] = ldo_mode_txrx */
  5,   /* field[5] = los_thresholds_en */
};
static const ProtobufCIntRange marvell__plr_advanced_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor marvell__plr_advanced_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_advanced_rules_t",
  "PlrAdvancedRulesT",
  "Marvell__PlrAdvancedRulesT",
  "marvell",
  sizeof(Marvell__PlrAdvancedRulesT),
  7,
  marvell__plr_advanced_rules_t__field_descriptors,
  marvell__plr_advanced_rules_t__field_indices_by_name,
  1,  marvell__plr_advanced_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_advanced_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_rx_qc_rules_t__field_descriptors[3] =
{
  {
    "snr_threshold_mm_enter",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRxQcRulesT, snr_threshold_mm_enter),
    &marvell__e_plr_rx_qc_snr_threshold__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "snr_threshold_mm_exit",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRxQcRulesT, snr_threshold_mm_exit),
    &marvell__e_plr_rx_qc_snr_threshold__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slc_err_limit",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRxQcRulesT, slc_err_limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_rx_qc_rules_t__field_indices_by_name[] = {
  2,   /* field[2] = slc_err_limit */
  0,   /* field[0] = snr_threshold_mm_enter */
  1,   /* field[1] = snr_threshold_mm_exit */
};
static const ProtobufCIntRange marvell__plr_rx_qc_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor marvell__plr_rx_qc_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_rx_qc_rules_t",
  "PlrRxQcRulesT",
  "Marvell__PlrRxQcRulesT",
  "marvell",
  sizeof(Marvell__PlrRxQcRulesT),
  3,
  marvell__plr_rx_qc_rules_t__field_descriptors,
  marvell__plr_rx_qc_rules_t__field_indices_by_name,
  1,  marvell__plr_rx_qc_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_rx_qc_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_lm_rules_t__field_descriptors[2] =
{
  {
    "fec_mode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLmRulesT, fec_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fec_interleave",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLmRulesT, fec_interleave),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_lm_rules_t__field_indices_by_name[] = {
  1,   /* field[1] = fec_interleave */
  0,   /* field[0] = fec_mode */
};
static const ProtobufCIntRange marvell__plr_lm_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor marvell__plr_lm_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_lm_rules_t",
  "PlrLmRulesT",
  "Marvell__PlrLmRulesT",
  "marvell",
  sizeof(Marvell__PlrLmRulesT),
  2,
  marvell__plr_lm_rules_t__field_descriptors,
  marvell__plr_lm_rules_t__field_indices_by_name,
  1,  marvell__plr_lm_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_lm_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_bundles_rules_t__field_descriptors[12] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrBundlesRulesT, n_id),
    offsetof(Marvell__PlrBundlesRulesT, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baud_rate",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrBundlesRulesT, n_baud_rate),
    offsetof(Marvell__PlrBundlesRulesT, baud_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operational_mode",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrBundlesRulesT, n_operational_mode),
    offsetof(Marvell__PlrBundlesRulesT, operational_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieee_demap",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Marvell__PlrBundlesRulesT, n_ieee_demap),
    offsetof(Marvell__PlrBundlesRulesT, ieee_demap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lrx_qc",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrBundlesRulesT, n_lrx_qc),
    offsetof(Marvell__PlrBundlesRulesT, lrx_qc),
    &marvell__plr_rx_qc_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hrx_qc",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrBundlesRulesT, n_hrx_qc),
    offsetof(Marvell__PlrBundlesRulesT, hrx_qc),
    &marvell__plr_rx_qc_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hrx",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrBundlesRulesT, n_hrx),
    offsetof(Marvell__PlrBundlesRulesT, hrx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "htx",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrBundlesRulesT, n_htx),
    offsetof(Marvell__PlrBundlesRulesT, htx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lrx",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrBundlesRulesT, n_lrx),
    offsetof(Marvell__PlrBundlesRulesT, lrx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ltx",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrBundlesRulesT, n_ltx),
    offsetof(Marvell__PlrBundlesRulesT, ltx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ltx_xbar",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrBundlesRulesT, n_ltx_xbar),
    offsetof(Marvell__PlrBundlesRulesT, ltx_xbar),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "htx_xbar",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrBundlesRulesT, n_htx_xbar),
    offsetof(Marvell__PlrBundlesRulesT, htx_xbar),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_bundles_rules_t__field_indices_by_name[] = {
  1,   /* field[1] = baud_rate */
  6,   /* field[6] = hrx */
  5,   /* field[5] = hrx_qc */
  7,   /* field[7] = htx */
  11,   /* field[11] = htx_xbar */
  0,   /* field[0] = id */
  3,   /* field[3] = ieee_demap */
  8,   /* field[8] = lrx */
  4,   /* field[4] = lrx_qc */
  9,   /* field[9] = ltx */
  10,   /* field[10] = ltx_xbar */
  2,   /* field[2] = operational_mode */
};
static const ProtobufCIntRange marvell__plr_bundles_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor marvell__plr_bundles_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_bundles_rules_t",
  "PlrBundlesRulesT",
  "Marvell__PlrBundlesRulesT",
  "marvell",
  sizeof(Marvell__PlrBundlesRulesT),
  12,
  marvell__plr_bundles_rules_t__field_descriptors,
  marvell__plr_bundles_rules_t__field_indices_by_name,
  1,  marvell__plr_bundles_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_bundles_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_lrx_rules_t__field_descriptors[14] =
{
  {
    "channel_enable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, channel_enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signalling",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, signalling),
    &marvell__e_plr_signal_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dsp_mode",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, dsp_mode),
    &marvell__e_plr_dsp_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gray_mapping",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, gray_mapping),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dfe_precoder_en",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, dfe_precoder_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "invert_chan",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, invert_chan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vga_tracking_en",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, vga_tracking_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oim_en",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, oim_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preamp_bias_ctrl",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, preamp_bias_ctrl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qc_all_dis",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, qc_all_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qc_hist_dis",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, qc_hist_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qc_slc_dis",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, qc_slc_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qc_snr_dis",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, qc_snr_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, status),
    &marvell__plr_rx_qc_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_lrx_rules_t__field_indices_by_name[] = {
  0,   /* field[0] = channel_enable */
  4,   /* field[4] = dfe_precoder_en */
  2,   /* field[2] = dsp_mode */
  3,   /* field[3] = gray_mapping */
  5,   /* field[5] = invert_chan */
  7,   /* field[7] = oim_en */
  8,   /* field[8] = preamp_bias_ctrl */
  9,   /* field[9] = qc_all_dis */
  10,   /* field[10] = qc_hist_dis */
  11,   /* field[11] = qc_slc_dis */
  12,   /* field[12] = qc_snr_dis */
  1,   /* field[1] = signalling */
  13,   /* field[13] = status */
  6,   /* field[6] = vga_tracking_en */
};
static const ProtobufCIntRange marvell__plr_lrx_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor marvell__plr_lrx_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_lrx_rules_t",
  "PlrLrxRulesT",
  "Marvell__PlrLrxRulesT",
  "marvell",
  sizeof(Marvell__PlrLrxRulesT),
  14,
  marvell__plr_lrx_rules_t__field_descriptors,
  marvell__plr_lrx_rules_t__field_indices_by_name,
  1,  marvell__plr_lrx_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_lrx_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_hrx_rules_t__field_descriptors[13] =
{
  {
    "channel_enable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, channel_enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gray_mapping",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, gray_mapping),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "invert_chan",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, invert_chan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_dsp_mode",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_dsp_mode),
    &marvell__e_plr_dsp_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_dfe_precoder_en",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_dfe_precoder_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_auto_ctle_en",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_auto_ctle_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_ctle_code",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_ctle_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_vga_tracking_en",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_vga_tracking_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_oim_en",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_oim_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_preamp_bias_ctrl",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_preamp_bias_ctrl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_pga_att_en",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_pga_att_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_qc_status",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_qc_status),
    &marvell__plr_rx_qc_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_vco_mode",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_vco_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_hrx_rules_t__field_indices_by_name[] = {
  0,   /* field[0] = channel_enable */
  1,   /* field[1] = gray_mapping */
  2,   /* field[2] = invert_chan */
  5,   /* field[5] = kr_auto_ctle_en */
  6,   /* field[6] = kr_ctle_code */
  4,   /* field[4] = kr_dfe_precoder_en */
  3,   /* field[3] = kr_dsp_mode */
  8,   /* field[8] = kr_oim_en */
  10,   /* field[10] = kr_pga_att_en */
  9,   /* field[9] = kr_preamp_bias_ctrl */
  11,   /* field[11] = kr_qc_status */
  7,   /* field[7] = kr_vga_tracking_en */
  12,   /* field[12] = sr_vco_mode */
};
static const ProtobufCIntRange marvell__plr_hrx_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor marvell__plr_hrx_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_hrx_rules_t",
  "PlrHrxRulesT",
  "Marvell__PlrHrxRulesT",
  "marvell",
  sizeof(Marvell__PlrHrxRulesT),
  13,
  marvell__plr_hrx_rules_t__field_descriptors,
  marvell__plr_hrx_rules_t__field_indices_by_name,
  1,  marvell__plr_hrx_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_hrx_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_tx_rules_t__field_descriptors[9] =
{
  {
    "channel_enable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, channel_enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "squelch_lock",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, squelch_lock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signalling",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, signalling),
    &marvell__e_plr_signal_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gray_mapping",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, gray_mapping),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "invert_chan",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, invert_chan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fir_tap",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Marvell__PlrTxRulesT, n_fir_tap),
    offsetof(Marvell__PlrTxRulesT, fir_tap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_eye1",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, inner_eye1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_eye2",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, inner_eye2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dfe_precoder_en",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, dfe_precoder_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_tx_rules_t__field_indices_by_name[] = {
  0,   /* field[0] = channel_enable */
  8,   /* field[8] = dfe_precoder_en */
  5,   /* field[5] = fir_tap */
  3,   /* field[3] = gray_mapping */
  6,   /* field[6] = inner_eye1 */
  7,   /* field[7] = inner_eye2 */
  4,   /* field[4] = invert_chan */
  2,   /* field[2] = signalling */
  1,   /* field[1] = squelch_lock */
};
static const ProtobufCIntRange marvell__plr_tx_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor marvell__plr_tx_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_tx_rules_t",
  "PlrTxRulesT",
  "Marvell__PlrTxRulesT",
  "marvell",
  sizeof(Marvell__PlrTxRulesT),
  9,
  marvell__plr_tx_rules_t__field_descriptors,
  marvell__plr_tx_rules_t__field_indices_by_name,
  1,  marvell__plr_tx_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_tx_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_rules_t__field_descriptors[22] =
{
  {
    "package_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, package_type),
    &marvell__e_plr_package_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operational_mode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, operational_mode),
    &marvell__e_plr_operational_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ref_clk_mode",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, ref_clk_mode),
    &marvell__e_plr_ref_clk_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ref_clk",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, ref_clk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baud_rate",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, baud_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sfec_en",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, sfec_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "show_debug_info",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, show_debug_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fw_dwld_timeout",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, fw_dwld_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieee_demap",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, ieee_demap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fw_warn_if_mismatched",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, fw_warn_if_mismatched),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sfp56_tp7_en",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, sfp56_tp7_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lrx_qc",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, lrx_qc),
    &marvell__plr_rx_qc_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hrx_qc",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, hrx_qc),
    &marvell__plr_rx_qc_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "htx_xbar",
    19,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesT, n_htx_xbar),
    offsetof(Marvell__PlrRulesT, htx_xbar),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ltx_xbar",
    20,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesT, n_ltx_xbar),
    offsetof(Marvell__PlrRulesT, ltx_xbar),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "advanded",
    21,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, advanded),
    &marvell__plr_advanced_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lm",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, lm),
    &marvell__plr_lm_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bundle",
    23,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesT, n_bundle),
    offsetof(Marvell__PlrRulesT, bundle),
    &marvell__plr_bundles_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lrx",
    24,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesT, n_lrx),
    offsetof(Marvell__PlrRulesT, lrx),
    &marvell__plr_lrx_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hrx",
    25,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesT, n_hrx),
    offsetof(Marvell__PlrRulesT, hrx),
    &marvell__plr_hrx_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ltx",
    26,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesT, n_ltx),
    offsetof(Marvell__PlrRulesT, ltx),
    &marvell__plr_tx_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "htx",
    27,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesT, n_htx),
    offsetof(Marvell__PlrRulesT, htx),
    &marvell__plr_tx_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_rules_t__field_indices_by_name[] = {
  15,   /* field[15] = advanded */
  4,   /* field[4] = baud_rate */
  17,   /* field[17] = bundle */
  7,   /* field[7] = fw_dwld_timeout */
  9,   /* field[9] = fw_warn_if_mismatched */
  19,   /* field[19] = hrx */
  12,   /* field[12] = hrx_qc */
  21,   /* field[21] = htx */
  13,   /* field[13] = htx_xbar */
  8,   /* field[8] = ieee_demap */
  16,   /* field[16] = lm */
  18,   /* field[18] = lrx */
  11,   /* field[11] = lrx_qc */
  20,   /* field[20] = ltx */
  14,   /* field[14] = ltx_xbar */
  1,   /* field[1] = operational_mode */
  0,   /* field[0] = package_type */
  3,   /* field[3] = ref_clk */
  2,   /* field[2] = ref_clk_mode */
  5,   /* field[5] = sfec_en */
  10,   /* field[10] = sfp56_tp7_en */
  6,   /* field[6] = show_debug_info */
};
static const ProtobufCIntRange marvell__plr_rules_t__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 19, 13 },
  { 0, 22 }
};
const ProtobufCMessageDescriptor marvell__plr_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_rules_t",
  "PlrRulesT",
  "Marvell__PlrRulesT",
  "marvell",
  sizeof(Marvell__PlrRulesT),
  22,
  marvell__plr_rules_t__field_descriptors,
  marvell__plr_rules_t__field_indices_by_name,
  2,  marvell__plr_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue marvell__e_plr_signal_mode__enum_values_by_number[2] =
{
  { "PLR_SIGNAL_MODE_PAM", "MARVELL__E_PLR_SIGNAL_MODE__PLR_SIGNAL_MODE_PAM", 0 },
  { "PLR_SIGNAL_MODE_NRZ", "MARVELL__E_PLR_SIGNAL_MODE__PLR_SIGNAL_MODE_NRZ", 1 },
};
static const ProtobufCIntRange marvell__e_plr_signal_mode__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex marvell__e_plr_signal_mode__enum_values_by_name[2] =
{
  { "PLR_SIGNAL_MODE_NRZ", 1 },
  { "PLR_SIGNAL_MODE_PAM", 0 },
};
const ProtobufCEnumDescriptor marvell__e_plr_signal_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_signal_mode",
  "e_plr_signal_mode",
  "Marvell__EPlrSignalMode",
  "marvell",
  2,
  marvell__e_plr_signal_mode__enum_values_by_number,
  2,
  marvell__e_plr_signal_mode__enum_values_by_name,
  1,
  marvell__e_plr_signal_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_package_type__enum_values_by_number[6] =
{
  { "PLR_PACKAGE_SKW_BARE_DIE", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_SKW_BARE_DIE", 0 },
  { "PLR_PACKAGE_TYPE_11x12_DD", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_11x12_DD", 1 },
  { "PLR_PACKAGE_TYPE_14x14_DD", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_14x14_DD", 2 },
  { "PLR_PACKAGE_TYPE_8x10_DD", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_8x10_DD", 3 },
  { "PLR_PACKAGE_TYPE_UNMAPPED", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_UNMAPPED", 4 },
  { "PLR_PACKAGE_TYPE_MAX", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_MAX", 5 },
};
static const ProtobufCIntRange marvell__e_plr_package_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex marvell__e_plr_package_type__enum_values_by_name[6] =
{
  { "PLR_PACKAGE_SKW_BARE_DIE", 0 },
  { "PLR_PACKAGE_TYPE_11x12_DD", 1 },
  { "PLR_PACKAGE_TYPE_14x14_DD", 2 },
  { "PLR_PACKAGE_TYPE_8x10_DD", 3 },
  { "PLR_PACKAGE_TYPE_MAX", 5 },
  { "PLR_PACKAGE_TYPE_UNMAPPED", 4 },
};
const ProtobufCEnumDescriptor marvell__e_plr_package_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_package_type",
  "e_plr_package_type",
  "Marvell__EPlrPackageType",
  "marvell",
  6,
  marvell__e_plr_package_type__enum_values_by_number,
  6,
  marvell__e_plr_package_type__enum_values_by_name,
  1,
  marvell__e_plr_package_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_operational_mode__enum_values_by_number[10] =
{
  { "PLR_MODE_DUPLEX_RETIMER", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_DUPLEX_RETIMER", 0 },
  { "PLR_MODE_FORWARD_GEARBOX", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_FORWARD_GEARBOX", 1 },
  { "PLR_MODE_LINE_RETIMER", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_LINE_RETIMER", 2 },
  { "PLR_MODE_HOST_RETIMER", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_HOST_RETIMER", 3 },
  { "PLR_MODE_LINE_PRBS", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_LINE_PRBS", 4 },
  { "PLR_MODE_HOST_PRBS", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_HOST_PRBS", 5 },
  { "PLR_MODE_DUAL_PRBS", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_DUAL_PRBS", 6 },
  { "PLR_MODE_INGRESS_PRBS", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_INGRESS_PRBS", 7 },
  { "PLR_MODE_EGRESS_PRBS", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_EGRESS_PRBS", 8 },
  { "PLR_MODE_SHALLOW_DUAL_LOOPBACK", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_SHALLOW_DUAL_LOOPBACK", 9 },
};
static const ProtobufCIntRange marvell__e_plr_operational_mode__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex marvell__e_plr_operational_mode__enum_values_by_name[10] =
{
  { "PLR_MODE_DUAL_PRBS", 6 },
  { "PLR_MODE_DUPLEX_RETIMER", 0 },
  { "PLR_MODE_EGRESS_PRBS", 8 },
  { "PLR_MODE_FORWARD_GEARBOX", 1 },
  { "PLR_MODE_HOST_PRBS", 5 },
  { "PLR_MODE_HOST_RETIMER", 3 },
  { "PLR_MODE_INGRESS_PRBS", 7 },
  { "PLR_MODE_LINE_PRBS", 4 },
  { "PLR_MODE_LINE_RETIMER", 2 },
  { "PLR_MODE_SHALLOW_DUAL_LOOPBACK", 9 },
};
const ProtobufCEnumDescriptor marvell__e_plr_operational_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_operational_mode",
  "e_plr_operational_mode",
  "Marvell__EPlrOperationalMode",
  "marvell",
  10,
  marvell__e_plr_operational_mode__enum_values_by_number,
  10,
  marvell__e_plr_operational_mode__enum_values_by_name,
  1,
  marvell__e_plr_operational_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_ref_clk_mode__enum_values_by_number[1] =
{
  { "PLR_CLK_MODE_LOCAL", "MARVELL__E_PLR_REF_CLK_MODE__PLR_CLK_MODE_LOCAL", 0 },
};
static const ProtobufCIntRange marvell__e_plr_ref_clk_mode__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex marvell__e_plr_ref_clk_mode__enum_values_by_name[1] =
{
  { "PLR_CLK_MODE_LOCAL", 0 },
};
const ProtobufCEnumDescriptor marvell__e_plr_ref_clk_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_ref_clk_mode",
  "e_plr_ref_clk_mode",
  "Marvell__EPlrRefClkMode",
  "marvell",
  1,
  marvell__e_plr_ref_clk_mode__enum_values_by_number,
  1,
  marvell__e_plr_ref_clk_mode__enum_values_by_name,
  1,
  marvell__e_plr_ref_clk_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_rx_qc_snr_threshold__enum_values_by_number[3] =
{
  { "PLR_RX_QC_SNR_THRESH_21dB", "MARVELL__E_PLR_RX_QC_SNR_THRESHOLD__PLR_RX_QC_SNR_THRESH_21dB", 210 },
  { "PLR_RX_QC_SNR_THRESH_22dB", "MARVELL__E_PLR_RX_QC_SNR_THRESHOLD__PLR_RX_QC_SNR_THRESH_22dB", 220 },
  { "PLR_RX_QC_SNR_THRESH_23dB", "MARVELL__E_PLR_RX_QC_SNR_THRESHOLD__PLR_RX_QC_SNR_THRESH_23dB", 230 },
};
static const ProtobufCIntRange marvell__e_plr_rx_qc_snr_threshold__value_ranges[] = {
{210, 0},{220, 1},{230, 2},{0, 3}
};
static const ProtobufCEnumValueIndex marvell__e_plr_rx_qc_snr_threshold__enum_values_by_name[3] =
{
  { "PLR_RX_QC_SNR_THRESH_21dB", 0 },
  { "PLR_RX_QC_SNR_THRESH_22dB", 1 },
  { "PLR_RX_QC_SNR_THRESH_23dB", 2 },
};
const ProtobufCEnumDescriptor marvell__e_plr_rx_qc_snr_threshold__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_rx_qc_snr_threshold",
  "e_plr_rx_qc_snr_threshold",
  "Marvell__EPlrRxQcSnrThreshold",
  "marvell",
  3,
  marvell__e_plr_rx_qc_snr_threshold__enum_values_by_number,
  3,
  marvell__e_plr_rx_qc_snr_threshold__enum_values_by_name,
  3,
  marvell__e_plr_rx_qc_snr_threshold__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_dsp_mode__enum_values_by_number[4] =
{
  { "PLR_DSP_MODE_SLC1_MPICAN_SLC2", "MARVELL__E_PLR_DSP_MODE__PLR_DSP_MODE_SLC1_MPICAN_SLC2", 8 },
  { "PLR_DSP_MODE_SLC1_RC_MPICAN_SLC2", "MARVELL__E_PLR_DSP_MODE__PLR_DSP_MODE_SLC1_RC_MPICAN_SLC2", 10 },
  { "PLR_DSP_MODE_DFE1_MPICAN_SLC2", "MARVELL__E_PLR_DSP_MODE__PLR_DSP_MODE_DFE1_MPICAN_SLC2", 13 },
  { "PLR_DSP_MODE_DFE1_RC_MPICAN_SLC2", "MARVELL__E_PLR_DSP_MODE__PLR_DSP_MODE_DFE1_RC_MPICAN_SLC2", 15 },
};
static const ProtobufCIntRange marvell__e_plr_dsp_mode__value_ranges[] = {
{8, 0},{10, 1},{13, 2},{15, 3},{0, 4}
};
static const ProtobufCEnumValueIndex marvell__e_plr_dsp_mode__enum_values_by_name[4] =
{
  { "PLR_DSP_MODE_DFE1_MPICAN_SLC2", 2 },
  { "PLR_DSP_MODE_DFE1_RC_MPICAN_SLC2", 3 },
  { "PLR_DSP_MODE_SLC1_MPICAN_SLC2", 0 },
  { "PLR_DSP_MODE_SLC1_RC_MPICAN_SLC2", 1 },
};
const ProtobufCEnumDescriptor marvell__e_plr_dsp_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_dsp_mode",
  "e_plr_dsp_mode",
  "Marvell__EPlrDspMode",
  "marvell",
  4,
  marvell__e_plr_dsp_mode__enum_values_by_number,
  4,
  marvell__e_plr_dsp_mode__enum_values_by_name,
  4,
  marvell__e_plr_dsp_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
