/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "demo2.pb-c.h"
void   marvell__plr_rules_t__init
                     (Marvell__PlrRulesT         *message)
{
  static const Marvell__PlrRulesT init_value = MARVELL__PLR_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_rules_t__get_packed_size
                     (const Marvell__PlrRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_rules_t__pack
                     (const Marvell__PlrRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_rules_t__pack_to_buffer
                     (const Marvell__PlrRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrRulesT *
       marvell__plr_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrRulesT *)
     protobuf_c_message_unpack (&marvell__plr_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_rules_t__free_unpacked
                     (Marvell__PlrRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor marvell__plr_rules_t__field_descriptors[11] =
{
  {
    "package_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, package_type),
    &marvell__e_plr_package_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operational_mode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, operational_mode),
    &marvell__e_plr_operational_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ref_clk_mode",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, ref_clk_mode),
    &marvell__e_plr_ref_clk_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ref_clk",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, ref_clk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baud_rate",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, baud_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sfec_en",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, sfec_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "show_debug_info",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, show_debug_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fw_dwld_timeout",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, fw_dwld_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieee_demap",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, ieee_demap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fw_warn_if_mismatched",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, fw_warn_if_mismatched),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sfp56_tp7_en",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesT, sfp56_tp7_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_rules_t__field_indices_by_name[] = {
  4,   /* field[4] = baud_rate */
  7,   /* field[7] = fw_dwld_timeout */
  9,   /* field[9] = fw_warn_if_mismatched */
  8,   /* field[8] = ieee_demap */
  1,   /* field[1] = operational_mode */
  0,   /* field[0] = package_type */
  3,   /* field[3] = ref_clk */
  2,   /* field[2] = ref_clk_mode */
  5,   /* field[5] = sfec_en */
  10,   /* field[10] = sfp56_tp7_en */
  6,   /* field[6] = show_debug_info */
};
static const ProtobufCIntRange marvell__plr_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor marvell__plr_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_rules_t",
  "PlrRulesT",
  "Marvell__PlrRulesT",
  "marvell",
  sizeof(Marvell__PlrRulesT),
  11,
  marvell__plr_rules_t__field_descriptors,
  marvell__plr_rules_t__field_indices_by_name,
  1,  marvell__plr_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue marvell__e_plr_package_type__enum_values_by_number[6] =
{
  { "PLR_PACKAGE_SKW_BARE_DIE", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_SKW_BARE_DIE", 0 },
  { "PLR_PACKAGE_TYPE_11x12_DD", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_11x12_DD", 1 },
  { "PLR_PACKAGE_TYPE_14x14_DD", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_14x14_DD", 2 },
  { "PLR_PACKAGE_TYPE_8x10_DD", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_8x10_DD", 3 },
  { "PLR_PACKAGE_TYPE_UNMAPPED", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_UNMAPPED", 4 },
  { "PLR_PACKAGE_TYPE_MAX", "MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_MAX", 5 },
};
static const ProtobufCIntRange marvell__e_plr_package_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex marvell__e_plr_package_type__enum_values_by_name[6] =
{
  { "PLR_PACKAGE_SKW_BARE_DIE", 0 },
  { "PLR_PACKAGE_TYPE_11x12_DD", 1 },
  { "PLR_PACKAGE_TYPE_14x14_DD", 2 },
  { "PLR_PACKAGE_TYPE_8x10_DD", 3 },
  { "PLR_PACKAGE_TYPE_MAX", 5 },
  { "PLR_PACKAGE_TYPE_UNMAPPED", 4 },
};
const ProtobufCEnumDescriptor marvell__e_plr_package_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_package_type",
  "e_plr_package_type",
  "Marvell__EPlrPackageType",
  "marvell",
  6,
  marvell__e_plr_package_type__enum_values_by_number,
  6,
  marvell__e_plr_package_type__enum_values_by_name,
  1,
  marvell__e_plr_package_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_operational_mode__enum_values_by_number[10] =
{
  { "PLR_MODE_DUPLEX_RETIMER", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_DUPLEX_RETIMER", 0 },
  { "PLR_MODE_FORWARD_GEARBOX", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_FORWARD_GEARBOX", 1 },
  { "PLR_MODE_LINE_RETIMER", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_LINE_RETIMER", 2 },
  { "PLR_MODE_HOST_RETIMER", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_HOST_RETIMER", 3 },
  { "PLR_MODE_LINE_PRBS", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_LINE_PRBS", 4 },
  { "PLR_MODE_HOST_PRBS", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_HOST_PRBS", 5 },
  { "PLR_MODE_DUAL_PRBS", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_DUAL_PRBS", 6 },
  { "PLR_MODE_INGRESS_PRBS", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_INGRESS_PRBS", 7 },
  { "PLR_MODE_EGRESS_PRBS", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_EGRESS_PRBS", 8 },
  { "PLR_MODE_SHALLOW_DUAL_LOOPBACK", "MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_SHALLOW_DUAL_LOOPBACK", 9 },
};
static const ProtobufCIntRange marvell__e_plr_operational_mode__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex marvell__e_plr_operational_mode__enum_values_by_name[10] =
{
  { "PLR_MODE_DUAL_PRBS", 6 },
  { "PLR_MODE_DUPLEX_RETIMER", 0 },
  { "PLR_MODE_EGRESS_PRBS", 8 },
  { "PLR_MODE_FORWARD_GEARBOX", 1 },
  { "PLR_MODE_HOST_PRBS", 5 },
  { "PLR_MODE_HOST_RETIMER", 3 },
  { "PLR_MODE_INGRESS_PRBS", 7 },
  { "PLR_MODE_LINE_PRBS", 4 },
  { "PLR_MODE_LINE_RETIMER", 2 },
  { "PLR_MODE_SHALLOW_DUAL_LOOPBACK", 9 },
};
const ProtobufCEnumDescriptor marvell__e_plr_operational_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_operational_mode",
  "e_plr_operational_mode",
  "Marvell__EPlrOperationalMode",
  "marvell",
  10,
  marvell__e_plr_operational_mode__enum_values_by_number,
  10,
  marvell__e_plr_operational_mode__enum_values_by_name,
  1,
  marvell__e_plr_operational_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_ref_clk_mode__enum_values_by_number[1] =
{
  { "PLR_CLK_MODE_LOCAL", "MARVELL__E_PLR_REF_CLK_MODE__PLR_CLK_MODE_LOCAL", 0 },
};
static const ProtobufCIntRange marvell__e_plr_ref_clk_mode__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex marvell__e_plr_ref_clk_mode__enum_values_by_name[1] =
{
  { "PLR_CLK_MODE_LOCAL", 0 },
};
const ProtobufCEnumDescriptor marvell__e_plr_ref_clk_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_ref_clk_mode",
  "e_plr_ref_clk_mode",
  "Marvell__EPlrRefClkMode",
  "marvell",
  1,
  marvell__e_plr_ref_clk_mode__enum_values_by_number,
  1,
  marvell__e_plr_ref_clk_mode__enum_values_by_name,
  1,
  marvell__e_plr_ref_clk_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
