/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo2.proto */

#ifndef PROTOBUF_C_demo2_2eproto__INCLUDED
#define PROTOBUF_C_demo2_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Marvell__PlrRulesT Marvell__PlrRulesT;


/* --- enums --- */

typedef enum _Marvell__EPlrPackageType {
  MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_SKW_BARE_DIE = 0,
  MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_11x12_DD = 1,
  MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_14x14_DD = 2,
  MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_8x10_DD = 3,
  MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_UNMAPPED = 4,
  MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_TYPE_MAX = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MARVELL__E_PLR_PACKAGE_TYPE)
} Marvell__EPlrPackageType;
typedef enum _Marvell__EPlrOperationalMode {
  MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_DUPLEX_RETIMER = 0,
  MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_FORWARD_GEARBOX = 1,
  MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_LINE_RETIMER = 2,
  MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_HOST_RETIMER = 3,
  MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_LINE_PRBS = 4,
  MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_HOST_PRBS = 5,
  MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_DUAL_PRBS = 6,
  MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_INGRESS_PRBS = 7,
  MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_EGRESS_PRBS = 8,
  MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_SHALLOW_DUAL_LOOPBACK = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MARVELL__E_PLR_OPERATIONAL_MODE)
} Marvell__EPlrOperationalMode;
typedef enum _Marvell__EPlrRefClkMode {
  MARVELL__E_PLR_REF_CLK_MODE__PLR_CLK_MODE_LOCAL = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MARVELL__E_PLR_REF_CLK_MODE)
} Marvell__EPlrRefClkMode;

/* --- messages --- */

struct  _Marvell__PlrRulesT
{
  ProtobufCMessage base;
  Marvell__EPlrPackageType package_type;
  Marvell__EPlrOperationalMode operational_mode;
  Marvell__EPlrRefClkMode ref_clk_mode;
  int32_t ref_clk;
  int32_t baud_rate;
  protobuf_c_boolean sfec_en;
  protobuf_c_boolean show_debug_info;
  uint32_t fw_dwld_timeout;
  protobuf_c_boolean ieee_demap;
  protobuf_c_boolean fw_warn_if_mismatched;
  protobuf_c_boolean sfp56_tp7_en;
};
#define MARVELL__PLR_RULES_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&marvell__plr_rules_t__descriptor) \
    , MARVELL__E_PLR_PACKAGE_TYPE__PLR_PACKAGE_SKW_BARE_DIE, MARVELL__E_PLR_OPERATIONAL_MODE__PLR_MODE_DUPLEX_RETIMER, MARVELL__E_PLR_REF_CLK_MODE__PLR_CLK_MODE_LOCAL, 0, 0, 0, 0, 0, 0, 0, 0 }


/* Marvell__PlrRulesT methods */
void   marvell__plr_rules_t__init
                     (Marvell__PlrRulesT         *message);
size_t marvell__plr_rules_t__get_packed_size
                     (const Marvell__PlrRulesT   *message);
size_t marvell__plr_rules_t__pack
                     (const Marvell__PlrRulesT   *message,
                      uint8_t             *out);
size_t marvell__plr_rules_t__pack_to_buffer
                     (const Marvell__PlrRulesT   *message,
                      ProtobufCBuffer     *buffer);
Marvell__PlrRulesT *
       marvell__plr_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   marvell__plr_rules_t__free_unpacked
                     (Marvell__PlrRulesT *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Marvell__PlrRulesT_Closure)
                 (const Marvell__PlrRulesT *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    marvell__e_plr_package_type__descriptor;
extern const ProtobufCEnumDescriptor    marvell__e_plr_operational_mode__descriptor;
extern const ProtobufCEnumDescriptor    marvell__e_plr_ref_clk_mode__descriptor;
extern const ProtobufCMessageDescriptor marvell__plr_rules_t__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_demo2_2eproto__INCLUDED */
