/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: address7.proto */

#ifndef PROTOBUF_C_address7_2eproto__INCLUDED
#define PROTOBUF_C_address7_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Tutorial__Person Tutorial__Person;
typedef struct _Tutorial__SuperPerson Tutorial__SuperPerson;


/* --- enums --- */


/* --- messages --- */

struct  _Tutorial__Person
{
  ProtobufCMessage base;
  int32_t rolld;
  int32_t id;
  size_t n_arr;
  int32_t *arr;
};
#define TUTORIAL__PERSON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tutorial__person__descriptor) \
    , 0, 0, 0,NULL }


struct  _Tutorial__SuperPerson
{
  ProtobufCMessage base;
  uint32_t money;
  size_t n_p1;
  Tutorial__Person **p1;
};
#define TUTORIAL__SUPER_PERSON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tutorial__super_person__descriptor) \
    , 0, 0,NULL }


/* Tutorial__Person methods */
void   tutorial__person__init
                     (Tutorial__Person         *message);
size_t tutorial__person__get_packed_size
                     (const Tutorial__Person   *message);
size_t tutorial__person__pack
                     (const Tutorial__Person   *message,
                      uint8_t             *out);
size_t tutorial__person__pack_to_buffer
                     (const Tutorial__Person   *message,
                      ProtobufCBuffer     *buffer);
Tutorial__Person *
       tutorial__person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tutorial__person__free_unpacked
                     (Tutorial__Person *message,
                      ProtobufCAllocator *allocator);
/* Tutorial__SuperPerson methods */
void   tutorial__super_person__init
                     (Tutorial__SuperPerson         *message);
size_t tutorial__super_person__get_packed_size
                     (const Tutorial__SuperPerson   *message);
size_t tutorial__super_person__pack
                     (const Tutorial__SuperPerson   *message,
                      uint8_t             *out);
size_t tutorial__super_person__pack_to_buffer
                     (const Tutorial__SuperPerson   *message,
                      ProtobufCBuffer     *buffer);
Tutorial__SuperPerson *
       tutorial__super_person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tutorial__super_person__free_unpacked
                     (Tutorial__SuperPerson *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Tutorial__Person_Closure)
                 (const Tutorial__Person *message,
                  void *closure_data);
typedef void (*Tutorial__SuperPerson_Closure)
                 (const Tutorial__SuperPerson *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor tutorial__person__descriptor;
extern const ProtobufCMessageDescriptor tutorial__super_person__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_address7_2eproto__INCLUDED */
