/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo1.proto */

#ifndef PROTOBUF_C_demo1_2eproto__INCLUDED
#define PROTOBUF_C_demo1_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Marvell__Rules Marvell__Rules;


/* --- enums --- */


/* --- messages --- */

struct  _Marvell__Rules
{
  ProtobufCMessage base;
  int32_t rolld;
  int32_t id;
};
#define MARVELL__RULES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&marvell__rules__descriptor) \
    , 0, 0 }


/* Marvell__Rules methods */
void   marvell__rules__init
                     (Marvell__Rules         *message);
size_t marvell__rules__get_packed_size
                     (const Marvell__Rules   *message);
size_t marvell__rules__pack
                     (const Marvell__Rules   *message,
                      uint8_t             *out);
size_t marvell__rules__pack_to_buffer
                     (const Marvell__Rules   *message,
                      ProtobufCBuffer     *buffer);
Marvell__Rules *
       marvell__rules__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   marvell__rules__free_unpacked
                     (Marvell__Rules *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Marvell__Rules_Closure)
                 (const Marvell__Rules *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor marvell__rules__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_demo1_2eproto__INCLUDED */
