/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo2.proto */

#ifndef PROTOBUF_C_demo2_2eproto__INCLUDED
#define PROTOBUF_C_demo2_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "demo1.pb-c.h"

typedef struct _Marvell__SuperRules Marvell__SuperRules;


/* --- enums --- */


/* --- messages --- */

struct  _Marvell__SuperRules
{
  ProtobufCMessage base;
  Marvell__Rules *r;
};
#define MARVELL__SUPER_RULES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&marvell__super_rules__descriptor) \
    , NULL }


/* Marvell__SuperRules methods */
void   marvell__super_rules__init
                     (Marvell__SuperRules         *message);
size_t marvell__super_rules__get_packed_size
                     (const Marvell__SuperRules   *message);
size_t marvell__super_rules__pack
                     (const Marvell__SuperRules   *message,
                      uint8_t             *out);
size_t marvell__super_rules__pack_to_buffer
                     (const Marvell__SuperRules   *message,
                      ProtobufCBuffer     *buffer);
Marvell__SuperRules *
       marvell__super_rules__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   marvell__super_rules__free_unpacked
                     (Marvell__SuperRules *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Marvell__SuperRules_Closure)
                 (const Marvell__SuperRules *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor marvell__super_rules__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_demo2_2eproto__INCLUDED */
