/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo1.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "demo1.pb-c.h"
void   marvell__rules__init
                     (Marvell__Rules         *message)
{
  static const Marvell__Rules init_value = MARVELL__RULES__INIT;
  *message = init_value;
}
size_t marvell__rules__get_packed_size
                     (const Marvell__Rules *message)
{
  assert(message->base.descriptor == &marvell__rules__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__rules__pack
                     (const Marvell__Rules *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__rules__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__rules__pack_to_buffer
                     (const Marvell__Rules *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__rules__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__Rules *
       marvell__rules__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__Rules *)
     protobuf_c_message_unpack (&marvell__rules__descriptor,
                                allocator, len, data);
}
void   marvell__rules__free_unpacked
                     (Marvell__Rules *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__rules__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor marvell__rules__field_descriptors[2] =
{
  {
    "rolld",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__Rules, rolld),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__Rules, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__rules__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = rolld */
};
static const ProtobufCIntRange marvell__rules__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor marvell__rules__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.rules",
  "Rules",
  "Marvell__Rules",
  "marvell",
  sizeof(Marvell__Rules),
  2,
  marvell__rules__field_descriptors,
  marvell__rules__field_indices_by_name,
  1,  marvell__rules__number_ranges,
  (ProtobufCMessageInit) marvell__rules__init,
  NULL,NULL,NULL    /* reserved[123] */
};
