/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "demo2.pb-c.h"
void   marvell__super_rules__init
                     (Marvell__SuperRules         *message)
{
  static const Marvell__SuperRules init_value = MARVELL__SUPER_RULES__INIT;
  *message = init_value;
}
size_t marvell__super_rules__get_packed_size
                     (const Marvell__SuperRules *message)
{
  assert(message->base.descriptor == &marvell__super_rules__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__super_rules__pack
                     (const Marvell__SuperRules *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__super_rules__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__super_rules__pack_to_buffer
                     (const Marvell__SuperRules *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__super_rules__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__SuperRules *
       marvell__super_rules__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__SuperRules *)
     protobuf_c_message_unpack (&marvell__super_rules__descriptor,
                                allocator, len, data);
}
void   marvell__super_rules__free_unpacked
                     (Marvell__SuperRules *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__super_rules__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor marvell__super_rules__field_descriptors[1] =
{
  {
    "r",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__SuperRules, r),
    &marvell__rules__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__super_rules__field_indices_by_name[] = {
  0,   /* field[0] = r */
};
static const ProtobufCIntRange marvell__super_rules__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor marvell__super_rules__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.super_rules",
  "SuperRules",
  "Marvell__SuperRules",
  "marvell",
  sizeof(Marvell__SuperRules),
  1,
  marvell__super_rules__field_descriptors,
  marvell__super_rules__field_indices_by_name,
  1,  marvell__super_rules__number_ranges,
  (ProtobufCMessageInit) marvell__super_rules__init,
  NULL,NULL,NULL    /* reserved[123] */
};
