/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: auto_gen_demo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "auto_gen_demo.pb-c.h"
void   marvell__plr_rx_qc_status_t__init
                     (Marvell__PlrRxQcStatusT         *message)
{
  static const Marvell__PlrRxQcStatusT init_value = MARVELL__PLR_RX_QC_STATUS_T__INIT;
  *message = init_value;
}
size_t marvell__plr_rx_qc_status_t__get_packed_size
                     (const Marvell__PlrRxQcStatusT *message)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_status_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_rx_qc_status_t__pack
                     (const Marvell__PlrRxQcStatusT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_status_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_rx_qc_status_t__pack_to_buffer
                     (const Marvell__PlrRxQcStatusT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_status_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrRxQcStatusT *
       marvell__plr_rx_qc_status_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrRxQcStatusT *)
     protobuf_c_message_unpack (&marvell__plr_rx_qc_status_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_rx_qc_status_t__free_unpacked
                     (Marvell__PlrRxQcStatusT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_rx_qc_status_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_rx_qc_rules_t__init
                     (Marvell__PlrRxQcRulesT         *message)
{
  static const Marvell__PlrRxQcRulesT init_value = MARVELL__PLR_RX_QC_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_rx_qc_rules_t__get_packed_size
                     (const Marvell__PlrRxQcRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_rx_qc_rules_t__pack
                     (const Marvell__PlrRxQcRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_rx_qc_rules_t__pack_to_buffer
                     (const Marvell__PlrRxQcRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_rx_qc_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrRxQcRulesT *
       marvell__plr_rx_qc_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrRxQcRulesT *)
     protobuf_c_message_unpack (&marvell__plr_rx_qc_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_rx_qc_rules_t__free_unpacked
                     (Marvell__PlrRxQcRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_rx_qc_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_lrx_rules_t__init
                     (Marvell__PlrLrxRulesT         *message)
{
  static const Marvell__PlrLrxRulesT init_value = MARVELL__PLR_LRX_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_lrx_rules_t__get_packed_size
                     (const Marvell__PlrLrxRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_lrx_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_lrx_rules_t__pack
                     (const Marvell__PlrLrxRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_lrx_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_lrx_rules_t__pack_to_buffer
                     (const Marvell__PlrLrxRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_lrx_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrLrxRulesT *
       marvell__plr_lrx_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrLrxRulesT *)
     protobuf_c_message_unpack (&marvell__plr_lrx_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_lrx_rules_t__free_unpacked
                     (Marvell__PlrLrxRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_lrx_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_hrx_rules_t__init
                     (Marvell__PlrHrxRulesT         *message)
{
  static const Marvell__PlrHrxRulesT init_value = MARVELL__PLR_HRX_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_hrx_rules_t__get_packed_size
                     (const Marvell__PlrHrxRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_hrx_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_hrx_rules_t__pack
                     (const Marvell__PlrHrxRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_hrx_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_hrx_rules_t__pack_to_buffer
                     (const Marvell__PlrHrxRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_hrx_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrHrxRulesT *
       marvell__plr_hrx_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrHrxRulesT *)
     protobuf_c_message_unpack (&marvell__plr_hrx_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_hrx_rules_t__free_unpacked
                     (Marvell__PlrHrxRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_hrx_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_tx_rules_t__init
                     (Marvell__PlrTxRulesT         *message)
{
  static const Marvell__PlrTxRulesT init_value = MARVELL__PLR_TX_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_tx_rules_t__get_packed_size
                     (const Marvell__PlrTxRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_tx_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_tx_rules_t__pack
                     (const Marvell__PlrTxRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_tx_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_tx_rules_t__pack_to_buffer
                     (const Marvell__PlrTxRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_tx_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrTxRulesT *
       marvell__plr_tx_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrTxRulesT *)
     protobuf_c_message_unpack (&marvell__plr_tx_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_tx_rules_t__free_unpacked
                     (Marvell__PlrTxRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_tx_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_advanced_rules_t__init
                     (Marvell__PlrAdvancedRulesT         *message)
{
  static const Marvell__PlrAdvancedRulesT init_value = MARVELL__PLR_ADVANCED_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_advanced_rules_t__get_packed_size
                     (const Marvell__PlrAdvancedRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_advanced_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_advanced_rules_t__pack
                     (const Marvell__PlrAdvancedRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_advanced_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_advanced_rules_t__pack_to_buffer
                     (const Marvell__PlrAdvancedRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_advanced_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrAdvancedRulesT *
       marvell__plr_advanced_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrAdvancedRulesT *)
     protobuf_c_message_unpack (&marvell__plr_advanced_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_advanced_rules_t__free_unpacked
                     (Marvell__PlrAdvancedRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_advanced_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_lm_rules_s__init
                     (Marvell__PlrLmRulesS         *message)
{
  static const Marvell__PlrLmRulesS init_value = MARVELL__PLR_LM_RULES_S__INIT;
  *message = init_value;
}
size_t marvell__plr_lm_rules_s__get_packed_size
                     (const Marvell__PlrLmRulesS *message)
{
  assert(message->base.descriptor == &marvell__plr_lm_rules_s__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_lm_rules_s__pack
                     (const Marvell__PlrLmRulesS *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_lm_rules_s__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_lm_rules_s__pack_to_buffer
                     (const Marvell__PlrLmRulesS *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_lm_rules_s__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrLmRulesS *
       marvell__plr_lm_rules_s__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrLmRulesS *)
     protobuf_c_message_unpack (&marvell__plr_lm_rules_s__descriptor,
                                allocator, len, data);
}
void   marvell__plr_lm_rules_s__free_unpacked
                     (Marvell__PlrLmRulesS *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_lm_rules_s__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_rules_t__init
                     (Marvell__PlrRulesT         *message)
{
  static const Marvell__PlrRulesT init_value = MARVELL__PLR_RULES_T__INIT;
  *message = init_value;
}
size_t marvell__plr_rules_t__get_packed_size
                     (const Marvell__PlrRulesT *message)
{
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_rules_t__pack
                     (const Marvell__PlrRulesT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_rules_t__pack_to_buffer
                     (const Marvell__PlrRulesT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrRulesT *
       marvell__plr_rules_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrRulesT *)
     protobuf_c_message_unpack (&marvell__plr_rules_t__descriptor,
                                allocator, len, data);
}
void   marvell__plr_rules_t__free_unpacked
                     (Marvell__PlrRulesT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_rules_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   marvell__plr_rules_s__init
                     (Marvell__PlrRulesS         *message)
{
  static const Marvell__PlrRulesS init_value = MARVELL__PLR_RULES_S__INIT;
  *message = init_value;
}
size_t marvell__plr_rules_s__get_packed_size
                     (const Marvell__PlrRulesS *message)
{
  assert(message->base.descriptor == &marvell__plr_rules_s__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t marvell__plr_rules_s__pack
                     (const Marvell__PlrRulesS *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &marvell__plr_rules_s__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t marvell__plr_rules_s__pack_to_buffer
                     (const Marvell__PlrRulesS *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &marvell__plr_rules_s__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Marvell__PlrRulesS *
       marvell__plr_rules_s__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Marvell__PlrRulesS *)
     protobuf_c_message_unpack (&marvell__plr_rules_s__descriptor,
                                allocator, len, data);
}
void   marvell__plr_rules_s__free_unpacked
                     (Marvell__PlrRulesS *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &marvell__plr_rules_s__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor marvell__plr_rx_qc_status_t__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRxQcStatusT, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_rx_qc_status_t__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange marvell__plr_rx_qc_status_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor marvell__plr_rx_qc_status_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_rx_qc_status_t",
  "PlrRxQcStatusT",
  "Marvell__PlrRxQcStatusT",
  "marvell",
  sizeof(Marvell__PlrRxQcStatusT),
  1,
  marvell__plr_rx_qc_status_t__field_descriptors,
  marvell__plr_rx_qc_status_t__field_indices_by_name,
  1,  marvell__plr_rx_qc_status_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_rx_qc_status_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_rx_qc_rules_t__field_descriptors[3] =
{
  {
    "snr_threshold_mm_enter",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRxQcRulesT, snr_threshold_mm_enter),
    &marvell__e_plr_rx_qc_snr_threshold__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "snr_threshold_mm_exit",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRxQcRulesT, snr_threshold_mm_exit),
    &marvell__e_plr_rx_qc_snr_threshold__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slc_err_limit",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRxQcRulesT, slc_err_limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_rx_qc_rules_t__field_indices_by_name[] = {
  2,   /* field[2] = slc_err_limit */
  0,   /* field[0] = snr_threshold_mm_enter */
  1,   /* field[1] = snr_threshold_mm_exit */
};
static const ProtobufCIntRange marvell__plr_rx_qc_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor marvell__plr_rx_qc_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_rx_qc_rules_t",
  "PlrRxQcRulesT",
  "Marvell__PlrRxQcRulesT",
  "marvell",
  sizeof(Marvell__PlrRxQcRulesT),
  3,
  marvell__plr_rx_qc_rules_t__field_descriptors,
  marvell__plr_rx_qc_rules_t__field_indices_by_name,
  1,  marvell__plr_rx_qc_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_rx_qc_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_lrx_rules_t__field_descriptors[14] =
{
  {
    "channel_enable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, channel_enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signalling",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, signalling),
    &marvell__e_plr_signal_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dsp_mode",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, dsp_mode),
    &marvell__e_plr_dsp_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gray_mapping",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, gray_mapping),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dfe_precoder_en",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, dfe_precoder_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "invert_chan",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, invert_chan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vga_tracking_en",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, vga_tracking_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oim_en",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, oim_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preamp_bias_ctrl",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, preamp_bias_ctrl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qc_all_dis",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, qc_all_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qc_hist_dis",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, qc_hist_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qc_slc_dis",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, qc_slc_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qc_snr_dis",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, qc_snr_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qc_status",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLrxRulesT, qc_status),
    &marvell__plr_rx_qc_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_lrx_rules_t__field_indices_by_name[] = {
  0,   /* field[0] = channel_enable */
  4,   /* field[4] = dfe_precoder_en */
  2,   /* field[2] = dsp_mode */
  3,   /* field[3] = gray_mapping */
  5,   /* field[5] = invert_chan */
  7,   /* field[7] = oim_en */
  8,   /* field[8] = preamp_bias_ctrl */
  9,   /* field[9] = qc_all_dis */
  10,   /* field[10] = qc_hist_dis */
  11,   /* field[11] = qc_slc_dis */
  12,   /* field[12] = qc_snr_dis */
  13,   /* field[13] = qc_status */
  1,   /* field[1] = signalling */
  6,   /* field[6] = vga_tracking_en */
};
static const ProtobufCIntRange marvell__plr_lrx_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor marvell__plr_lrx_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_lrx_rules_t",
  "PlrLrxRulesT",
  "Marvell__PlrLrxRulesT",
  "marvell",
  sizeof(Marvell__PlrLrxRulesT),
  14,
  marvell__plr_lrx_rules_t__field_descriptors,
  marvell__plr_lrx_rules_t__field_indices_by_name,
  1,  marvell__plr_lrx_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_lrx_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_hrx_rules_t__field_descriptors[36] =
{
  {
    "channel_enable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, channel_enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signalling",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, signalling),
    &marvell__e_plr_signal_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gray_mapping",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, gray_mapping),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "invert_chan",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, invert_chan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_dsp_mode",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_dsp_mode),
    &marvell__e_plr_dsp_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_dfe_precoder_en",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_dfe_precoder_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_auto_ctle_en",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_auto_ctle_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_ctle_code",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_ctle_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_vga_tracking_en",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_vga_tracking_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_oim_en",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_oim_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_preamp_bias_ctrl",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_preamp_bias_ctrl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_pga_att_en",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_pga_att_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_qc_all_dis",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_qc_all_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_qc_hist_dis",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_qc_hist_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_qc_slc_dis",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_qc_slc_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_qc_snr_dis",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_qc_snr_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kr_qc_status",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, kr_qc_status),
    &marvell__plr_rx_qc_status_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_skip_adapt",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_skip_adapt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_ctle_adapt_dis",
    19,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_ctle_adapt_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_ctle_override",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_ctle_override),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_ctle_c_adapt_en",
    21,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_ctle_c_adapt_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_ctle_r_adapt_dis",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_ctle_r_adapt_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_lfeq_adapt_dis",
    23,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_lfeq_adapt_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_lfeq_override",
    24,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_lfeq_override),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_dfe_adapt_dis",
    25,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_dfe_adapt_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_data_skew_adapt_dis",
    26,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_data_skew_adapt_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_edge_skew_adapt_dis",
    27,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_edge_skew_adapt_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_slc_adapt_dis",
    28,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_slc_adapt_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_edge_off_adapt_dis",
    29,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_edge_off_adapt_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_agc_adapt_dis",
    30,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_agc_adapt_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_vco_temp_cal_dis",
    31,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_vco_temp_cal_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_afe_low_bw",
    32,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_afe_low_bw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_afe_bw_adapt_dis",
    33,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_afe_bw_adapt_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_dc_off_adapt_dis",
    34,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_dc_off_adapt_dis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_vco_mode",
    35,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_vco_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sr_lfeq_adapt_dis_after_init_adapt",
    36,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrHrxRulesT, sr_lfeq_adapt_dis_after_init_adapt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_hrx_rules_t__field_indices_by_name[] = {
  0,   /* field[0] = channel_enable */
  2,   /* field[2] = gray_mapping */
  3,   /* field[3] = invert_chan */
  6,   /* field[6] = kr_auto_ctle_en */
  7,   /* field[7] = kr_ctle_code */
  5,   /* field[5] = kr_dfe_precoder_en */
  4,   /* field[4] = kr_dsp_mode */
  9,   /* field[9] = kr_oim_en */
  11,   /* field[11] = kr_pga_att_en */
  10,   /* field[10] = kr_preamp_bias_ctrl */
  12,   /* field[12] = kr_qc_all_dis */
  13,   /* field[13] = kr_qc_hist_dis */
  14,   /* field[14] = kr_qc_slc_dis */
  15,   /* field[15] = kr_qc_snr_dis */
  16,   /* field[16] = kr_qc_status */
  8,   /* field[8] = kr_vga_tracking_en */
  1,   /* field[1] = signalling */
  32,   /* field[32] = sr_afe_bw_adapt_dis */
  31,   /* field[31] = sr_afe_low_bw */
  29,   /* field[29] = sr_agc_adapt_dis */
  18,   /* field[18] = sr_ctle_adapt_dis */
  20,   /* field[20] = sr_ctle_c_adapt_en */
  19,   /* field[19] = sr_ctle_override */
  21,   /* field[21] = sr_ctle_r_adapt_dis */
  25,   /* field[25] = sr_data_skew_adapt_dis */
  33,   /* field[33] = sr_dc_off_adapt_dis */
  24,   /* field[24] = sr_dfe_adapt_dis */
  28,   /* field[28] = sr_edge_off_adapt_dis */
  26,   /* field[26] = sr_edge_skew_adapt_dis */
  22,   /* field[22] = sr_lfeq_adapt_dis */
  35,   /* field[35] = sr_lfeq_adapt_dis_after_init_adapt */
  23,   /* field[23] = sr_lfeq_override */
  17,   /* field[17] = sr_skip_adapt */
  27,   /* field[27] = sr_slc_adapt_dis */
  34,   /* field[34] = sr_vco_mode */
  30,   /* field[30] = sr_vco_temp_cal_dis */
};
static const ProtobufCIntRange marvell__plr_hrx_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 36 }
};
const ProtobufCMessageDescriptor marvell__plr_hrx_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_hrx_rules_t",
  "PlrHrxRulesT",
  "Marvell__PlrHrxRulesT",
  "marvell",
  sizeof(Marvell__PlrHrxRulesT),
  36,
  marvell__plr_hrx_rules_t__field_descriptors,
  marvell__plr_hrx_rules_t__field_indices_by_name,
  1,  marvell__plr_hrx_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_hrx_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_tx_rules_t__field_descriptors[9] =
{
  {
    "channel_enable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, channel_enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "squelch_lock",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, squelch_lock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signalling",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, signalling),
    &marvell__e_plr_signal_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gray_mapping",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, gray_mapping),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "invert_chan",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, invert_chan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fir_tap",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Marvell__PlrTxRulesT, n_fir_tap),
    offsetof(Marvell__PlrTxRulesT, fir_tap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_eye1",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, inner_eye1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_eye2",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, inner_eye2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dfe_precoder_en",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrTxRulesT, dfe_precoder_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_tx_rules_t__field_indices_by_name[] = {
  0,   /* field[0] = channel_enable */
  8,   /* field[8] = dfe_precoder_en */
  5,   /* field[5] = fir_tap */
  3,   /* field[3] = gray_mapping */
  6,   /* field[6] = inner_eye1 */
  7,   /* field[7] = inner_eye2 */
  4,   /* field[4] = invert_chan */
  2,   /* field[2] = signalling */
  1,   /* field[1] = squelch_lock */
};
static const ProtobufCIntRange marvell__plr_tx_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor marvell__plr_tx_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_tx_rules_t",
  "PlrTxRulesT",
  "Marvell__PlrTxRulesT",
  "marvell",
  sizeof(Marvell__PlrTxRulesT),
  9,
  marvell__plr_tx_rules_t__field_descriptors,
  marvell__plr_tx_rules_t__field_indices_by_name,
  1,  marvell__plr_tx_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_tx_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_advanced_rules_t__field_descriptors[7] =
{
  {
    "fll_low_bw_en",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, fll_low_bw_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ldo_mode_pll",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, ldo_mode_pll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ldo_mode_txrx",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, ldo_mode_txrx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gck_en",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, gck_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "breakout_en",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, breakout_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "los_thresholds_en",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, los_thresholds_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avs_en",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrAdvancedRulesT, avs_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_advanced_rules_t__field_indices_by_name[] = {
  6,   /* field[6] = avs_en */
  4,   /* field[4] = breakout_en */
  0,   /* field[0] = fll_low_bw_en */
  3,   /* field[3] = gck_en */
  1,   /* field[1] = ldo_mode_pll */
  2,   /* field[2] = ldo_mode_txrx */
  5,   /* field[5] = los_thresholds_en */
};
static const ProtobufCIntRange marvell__plr_advanced_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor marvell__plr_advanced_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_advanced_rules_t",
  "PlrAdvancedRulesT",
  "Marvell__PlrAdvancedRulesT",
  "marvell",
  sizeof(Marvell__PlrAdvancedRulesT),
  7,
  marvell__plr_advanced_rules_t__field_descriptors,
  marvell__plr_advanced_rules_t__field_indices_by_name,
  1,  marvell__plr_advanced_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_advanced_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_lm_rules_s__field_descriptors[2] =
{
  {
    "fec_mode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLmRulesS, fec_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fec_interleave",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrLmRulesS, fec_interleave),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_lm_rules_s__field_indices_by_name[] = {
  1,   /* field[1] = fec_interleave */
  0,   /* field[0] = fec_mode */
};
static const ProtobufCIntRange marvell__plr_lm_rules_s__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor marvell__plr_lm_rules_s__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_lm_rules_s",
  "PlrLmRulesS",
  "Marvell__PlrLmRulesS",
  "marvell",
  sizeof(Marvell__PlrLmRulesS),
  2,
  marvell__plr_lm_rules_s__field_descriptors,
  marvell__plr_lm_rules_s__field_indices_by_name,
  1,  marvell__plr_lm_rules_s__number_ranges,
  (ProtobufCMessageInit) marvell__plr_lm_rules_s__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_rules_t__field_descriptors[12] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesT, n_id),
    offsetof(Marvell__PlrRulesT, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baud_rate",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesT, n_baud_rate),
    offsetof(Marvell__PlrRulesT, baud_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operational_mode",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesT, n_operational_mode),
    offsetof(Marvell__PlrRulesT, operational_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieee_demap",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Marvell__PlrRulesT, n_ieee_demap),
    offsetof(Marvell__PlrRulesT, ieee_demap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lrx_qc",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesT, n_lrx_qc),
    offsetof(Marvell__PlrRulesT, lrx_qc),
    &marvell__plr_rx_qc_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hrx_qc",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesT, n_hrx_qc),
    offsetof(Marvell__PlrRulesT, hrx_qc),
    &marvell__plr_rx_qc_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hrx",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesT, n_hrx),
    offsetof(Marvell__PlrRulesT, hrx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "htx",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesT, n_htx),
    offsetof(Marvell__PlrRulesT, htx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lrx",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesT, n_lrx),
    offsetof(Marvell__PlrRulesT, lrx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ltx",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesT, n_ltx),
    offsetof(Marvell__PlrRulesT, ltx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ltx_xbar",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesT, n_ltx_xbar),
    offsetof(Marvell__PlrRulesT, ltx_xbar),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "htx_xbar",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesT, n_htx_xbar),
    offsetof(Marvell__PlrRulesT, htx_xbar),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_rules_t__field_indices_by_name[] = {
  1,   /* field[1] = baud_rate */
  6,   /* field[6] = hrx */
  5,   /* field[5] = hrx_qc */
  7,   /* field[7] = htx */
  11,   /* field[11] = htx_xbar */
  0,   /* field[0] = id */
  3,   /* field[3] = ieee_demap */
  8,   /* field[8] = lrx */
  4,   /* field[4] = lrx_qc */
  9,   /* field[9] = ltx */
  10,   /* field[10] = ltx_xbar */
  2,   /* field[2] = operational_mode */
};
static const ProtobufCIntRange marvell__plr_rules_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor marvell__plr_rules_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_rules_t",
  "PlrRulesT",
  "Marvell__PlrRulesT",
  "marvell",
  sizeof(Marvell__PlrRulesT),
  12,
  marvell__plr_rules_t__field_descriptors,
  marvell__plr_rules_t__field_indices_by_name,
  1,  marvell__plr_rules_t__number_ranges,
  (ProtobufCMessageInit) marvell__plr_rules_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor marvell__plr_rules_s__field_descriptors[22] =
{
  {
    "package_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, package_type),
    &marvell__e_plr_package_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operational_mode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, operational_mode),
    &marvell__e_plr_operational_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ref_clk_mode",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, ref_clk_mode),
    &marvell__e_plr_ref_clk_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ref_clk",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, ref_clk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baud_rate",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, baud_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sfec_en",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, sfec_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bundle",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesS, n_bundle),
    offsetof(Marvell__PlrRulesS, bundle),
    &marvell__plr_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lrx_qc",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, lrx_qc),
    &marvell__plr_rx_qc_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hrx_qc",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, hrx_qc),
    &marvell__plr_rx_qc_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "show_debug_info",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, show_debug_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fw_dwld_timeout",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, fw_dwld_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ieee_demap",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, ieee_demap),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fw_warn_if_mismatched",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, fw_warn_if_mismatched),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sfp56_tp7_en",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, sfp56_tp7_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lrx",
    15,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesS, n_lrx),
    offsetof(Marvell__PlrRulesS, lrx),
    &marvell__plr_lrx_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hrx",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesS, n_hrx),
    offsetof(Marvell__PlrRulesS, hrx),
    &marvell__plr_hrx_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ltx",
    17,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesS, n_ltx),
    offsetof(Marvell__PlrRulesS, ltx),
    &marvell__plr_tx_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "htx",
    18,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Marvell__PlrRulesS, n_htx),
    offsetof(Marvell__PlrRulesS, htx),
    &marvell__plr_tx_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "htx_xbar",
    19,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesS, n_htx_xbar),
    offsetof(Marvell__PlrRulesS, htx_xbar),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ltx_xbar",
    20,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Marvell__PlrRulesS, n_ltx_xbar),
    offsetof(Marvell__PlrRulesS, ltx_xbar),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "advanced",
    21,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, advanced),
    &marvell__plr_advanced_rules_t__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lm",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Marvell__PlrRulesS, lm),
    &marvell__plr_lm_rules_s__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned marvell__plr_rules_s__field_indices_by_name[] = {
  20,   /* field[20] = advanced */
  4,   /* field[4] = baud_rate */
  6,   /* field[6] = bundle */
  10,   /* field[10] = fw_dwld_timeout */
  12,   /* field[12] = fw_warn_if_mismatched */
  15,   /* field[15] = hrx */
  8,   /* field[8] = hrx_qc */
  17,   /* field[17] = htx */
  18,   /* field[18] = htx_xbar */
  11,   /* field[11] = ieee_demap */
  21,   /* field[21] = lm */
  14,   /* field[14] = lrx */
  7,   /* field[7] = lrx_qc */
  16,   /* field[16] = ltx */
  19,   /* field[19] = ltx_xbar */
  1,   /* field[1] = operational_mode */
  0,   /* field[0] = package_type */
  3,   /* field[3] = ref_clk */
  2,   /* field[2] = ref_clk_mode */
  5,   /* field[5] = sfec_en */
  13,   /* field[13] = sfp56_tp7_en */
  9,   /* field[9] = show_debug_info */
};
static const ProtobufCIntRange marvell__plr_rules_s__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 22 }
};
const ProtobufCMessageDescriptor marvell__plr_rules_s__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "marvell.plr_rules_s",
  "PlrRulesS",
  "Marvell__PlrRulesS",
  "marvell",
  sizeof(Marvell__PlrRulesS),
  22,
  marvell__plr_rules_s__field_descriptors,
  marvell__plr_rules_s__field_indices_by_name,
  1,  marvell__plr_rules_s__number_ranges,
  (ProtobufCMessageInit) marvell__plr_rules_s__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue marvell__e_plr_package_type__enum_values_by_number[1] =
{
  { "A", "MARVELL__E_PLR_PACKAGE_TYPE__A", 0 },
};
static const ProtobufCIntRange marvell__e_plr_package_type__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex marvell__e_plr_package_type__enum_values_by_name[1] =
{
  { "A", 0 },
};
const ProtobufCEnumDescriptor marvell__e_plr_package_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_package_type",
  "e_plr_package_type",
  "Marvell__EPlrPackageType",
  "marvell",
  1,
  marvell__e_plr_package_type__enum_values_by_number,
  1,
  marvell__e_plr_package_type__enum_values_by_name,
  1,
  marvell__e_plr_package_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_operational_mode__enum_values_by_number[1] =
{
  { "B", "MARVELL__E_PLR_OPERATIONAL_MODE__B", 1 },
};
static const ProtobufCIntRange marvell__e_plr_operational_mode__value_ranges[] = {
{1, 0},{0, 1}
};
static const ProtobufCEnumValueIndex marvell__e_plr_operational_mode__enum_values_by_name[1] =
{
  { "B", 0 },
};
const ProtobufCEnumDescriptor marvell__e_plr_operational_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_operational_mode",
  "e_plr_operational_mode",
  "Marvell__EPlrOperationalMode",
  "marvell",
  1,
  marvell__e_plr_operational_mode__enum_values_by_number,
  1,
  marvell__e_plr_operational_mode__enum_values_by_name,
  1,
  marvell__e_plr_operational_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_ref_clk_mode__enum_values_by_number[1] =
{
  { "C", "MARVELL__E_PLR_REF_CLK_MODE__C", 2 },
};
static const ProtobufCIntRange marvell__e_plr_ref_clk_mode__value_ranges[] = {
{2, 0},{0, 1}
};
static const ProtobufCEnumValueIndex marvell__e_plr_ref_clk_mode__enum_values_by_name[1] =
{
  { "C", 0 },
};
const ProtobufCEnumDescriptor marvell__e_plr_ref_clk_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_ref_clk_mode",
  "e_plr_ref_clk_mode",
  "Marvell__EPlrRefClkMode",
  "marvell",
  1,
  marvell__e_plr_ref_clk_mode__enum_values_by_number,
  1,
  marvell__e_plr_ref_clk_mode__enum_values_by_name,
  1,
  marvell__e_plr_ref_clk_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_rx_qc_snr_threshold__enum_values_by_number[1] =
{
  { "D", "MARVELL__E_PLR_RX_QC_SNR_THRESHOLD__D", 44 },
};
static const ProtobufCIntRange marvell__e_plr_rx_qc_snr_threshold__value_ranges[] = {
{44, 0},{0, 1}
};
static const ProtobufCEnumValueIndex marvell__e_plr_rx_qc_snr_threshold__enum_values_by_name[1] =
{
  { "D", 0 },
};
const ProtobufCEnumDescriptor marvell__e_plr_rx_qc_snr_threshold__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_rx_qc_snr_threshold",
  "e_plr_rx_qc_snr_threshold",
  "Marvell__EPlrRxQcSnrThreshold",
  "marvell",
  1,
  marvell__e_plr_rx_qc_snr_threshold__enum_values_by_number,
  1,
  marvell__e_plr_rx_qc_snr_threshold__enum_values_by_name,
  1,
  marvell__e_plr_rx_qc_snr_threshold__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_signal_mode__enum_values_by_number[1] =
{
  { "E", "MARVELL__E_PLR_SIGNAL_MODE__E", 54 },
};
static const ProtobufCIntRange marvell__e_plr_signal_mode__value_ranges[] = {
{54, 0},{0, 1}
};
static const ProtobufCEnumValueIndex marvell__e_plr_signal_mode__enum_values_by_name[1] =
{
  { "E", 0 },
};
const ProtobufCEnumDescriptor marvell__e_plr_signal_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_signal_mode",
  "e_plr_signal_mode",
  "Marvell__EPlrSignalMode",
  "marvell",
  1,
  marvell__e_plr_signal_mode__enum_values_by_number,
  1,
  marvell__e_plr_signal_mode__enum_values_by_name,
  1,
  marvell__e_plr_signal_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue marvell__e_plr_dsp_mode__enum_values_by_number[1] =
{
  { "F", "MARVELL__E_PLR_DSP_MODE__F", 64 },
};
static const ProtobufCIntRange marvell__e_plr_dsp_mode__value_ranges[] = {
{64, 0},{0, 1}
};
static const ProtobufCEnumValueIndex marvell__e_plr_dsp_mode__enum_values_by_name[1] =
{
  { "F", 0 },
};
const ProtobufCEnumDescriptor marvell__e_plr_dsp_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "marvell.e_plr_dsp_mode",
  "e_plr_dsp_mode",
  "Marvell__EPlrDspMode",
  "marvell",
  1,
  marvell__e_plr_dsp_mode__enum_values_by_number,
  1,
  marvell__e_plr_dsp_mode__enum_values_by_name,
  1,
  marvell__e_plr_dsp_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
